.PHONY: clean All

All:
	@echo "----------Building project:[ ChallangeSelection - Debug ]----------"
	@cd "ChallangeSelection" && "$(MAKE)" -f  "ChallangeSelection.mk"
clean:
	@echo "----------Cleaning project:[ ChallangeSelection - Debug ]----------"
	@cd "ChallangeSelection" && "$(MAKE)" -f  "ChallangeSelection.mk" clean
