.PHONY: clean All

All:
	@echo "----------Building project:[ LogarithmsBasic - Debug ]----------"
	@cd "LogarithmsBasic" && "$(MAKE)" -f  "LogarithmsBasic.mk"
clean:
	@echo "----------Cleaning project:[ LogarithmsBasic - Debug ]----------"
	@cd "LogarithmsBasic" && "$(MAKE)" -f  "LogarithmsBasic.mk" clean
