.PHONY: clean All

All:
	@echo "----------Building project:[ AbsoluteSum - Debug ]----------"
	@cd "AbsoluteSum" && "$(MAKE)" -f  "AbsoluteSum.mk"
clean:
	@echo "----------Cleaning project:[ AbsoluteSum - Debug ]----------"
	@cd "AbsoluteSum" && "$(MAKE)" -f  "AbsoluteSum.mk" clean
