.PHONY: clean All

All:
	@echo "----------Building project:[ CanYouDrive - Debug ]----------"
	@cd "CanYouDrive" && "$(MAKE)" -f  "CanYouDrive.mk"
clean:
	@echo "----------Cleaning project:[ CanYouDrive - Debug ]----------"
	@cd "CanYouDrive" && "$(MAKE)" -f  "CanYouDrive.mk" clean
